# $Id: Makefile,v 1.1.1.1 2009/10/09 03:04:19 jack Exp $

BUILD=	autocommit.html \
	clear.html \
	disk.html \
	intro.html \
	isolation.html \
	joinenv.html \
	lockstat.html \
	mutex.html \
	toc.html

all: ${BUILD}
