

#
# Makefile for the Marvell Phone Device Driver Test Module
#
#

ifeq ($(CONFIG_ARCH_FEROCEON),y)
	include $(srctree)/arch/arm/mach-kirkwood/config/mvRules.mk
endif

obj-$(CONFIG_MV_INCLUDE_TDM) += tdm_dev.o
