# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:22 jack Exp $

BUILD=	app_dispatch.html checkpoint.html cxx.html disk.html excl.html \
	fop.html hash_nelem.html incomplete.html intro.html java.html \
	log_register.html log_stat.html memp_sync.html toc.html

all: ${BUILD}
