# $Id: Makefile,v 1.1.1.1 2009/10/09 03:03:57 jack Exp $

COMMON=	mutex_alloc.html \
	mutex_free.html \
	mutex_list.html \
	mutex_lock.html \
	mutex_set_align.html \
	mutex_set_max.html \
	mutex_set_tas_spins.html \
	mutex_stat.html \
	mutex_unlock.html
