# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:23 jack Exp $

BUILD=  asr.html cxx.html deadlock.html disk.html env.html intro.html \
	java.html lock.html lock_id_free.html log.html mp.html rpc.html \
	set_lk_max.html toc.html txn.html

all: ${BUILD}
