.TH WARNQUOTA 8
.SH NAME
warnquota \- send mail to users over quota
.SH SYNOPSIS
.B warnquota
[
.B \-ugsid
] [
.B \-F
.I quotaformat
] [
.B \-q
.I quotatab
] [
.B \-c
.I configfile
] [
.B \-a
.I adminsfile
]
.SH DESCRIPTION
.B warnquota
checks the disk quota for each local filesystem and mails a warning
message to those users who have reached their softlimit.
It is typically run via
.BR cron (8).
.TP
.B -F, --format=\f2quotaformat\f1
Perform setting for specified format (ie. don't perform format autodetection).
Possible format names are:
.B vfsold
(version 1 quota),
.B vfsv0
(version 2 quota),
.B rpc
(quota over NFS),
.B xfs
(quota on XFS filesystem)
.TP
.B -q, --quota-tab=\f2quotatab\f1
Use
.I quotatab
instead of
.I /etc/quotatab
as file with device description strings (see example file for syntax).
.TP
.B -c, --config=\f2configfile\f1
Use
.I configfile
instead of
.I /etc/warnquota.conf
as configuration file (see example file for syntax).
.TP
.B -a, --admins-file=\f2adminsfile\f1
Use
.I adminsfile
instead of
.I /etc/quotagrpadmins
as a file with administrators of the groups.
.TP
.B -u, --user
check whether users are not exceeding quotas (default).
.TP
.B -g, --group
check whether groups are not exceeding quotas. If group is exceeding quota
a mail is sent to the user specified in /etc/quotagrpadmins.
.TP
.B -s, --human-readable
Try to report used space, number of used inodes and limits in more appropriate units
than the default ones.
.TP
.B -i, --no-autofs
ignore mountpoints mounted by automounter.
.TP
.B -d, --no-details
do not attach quota report in email.
.SH FILES
.PD 0
.TP 20
.B aquota.user
quota file at the filesystem root (version 2 quota, non-XFS filesystems)
.TP
.B quota.user
quota file at the filesystem root (version 1 quota, non-XFS filesystems)
.TP
.B /etc/warnquota.conf
configuration file
.TP
.B /etc/quotatab
device description
.TP
.B /etc/quotagrpadmins
administrators of the groups
.TP
.B /etc/mtab
default filesystems
.TP
.B /etc/passwd
default set of users
.PD
.SH "SEE ALSO"
.BR quota (1),
.BR cron (8),
.BR edquota (8).
.SH AUTHORS
.BR warnquota (8)
was written by Marco van Wieringen <mvw@planets.elm.net>, modifications by Jan Kara <jack@suse.cz>.
This reference page written by Heiko Schlittermann <heiko@lotte.sax.de>, modifications by Jan Kara
