# $Id: Makefile,v 1.1.1.1 2009/10/09 03:04:16 jack Exp $

BUILD=	alloc.html bigfile.html conflict.html disk.html getswap.html \
	gettype.html intro.html memp_fget.html rpc.html shared.html \
	toc.html txn_prepare.html

all: ${BUILD}
