# $Id: Makefile,v 1.1.1.1 2009/10/09 03:04:19 jack Exp $

BUILD=	alive.html \
	applog.html \
	collect.html \
	config.html \
	deprecate.html \
	disk.html \
	elect.html \
	intro.html \
	memp.html \
	pagesize.html \
	paniccall.html \
	rep_event.html \
	rep_set.html \
	source.html \
	toc.html

all: ${BUILD}
