MAKEFLAGS=-s --no-print-directory
srcdir = .
top_srcdir = ../../..
pkgdatadir = $(datadir)/amule
pkglibdir = $(libdir)/amule
pkgincludedir = $(includedir)/amule
top_builddir = ../../..
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = arm-mv5sft-linux-gnueabi
noinst_PROGRAMS = mulefileview$(EXEEXT)
subdir = src/utils/fileview
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/GeoIP.m4 \
	$(top_srcdir)/m4/build-tools.m4 $(top_srcdir)/m4/codeset.m4 \
	$(top_srcdir)/m4/cryptopp.m4 $(top_srcdir)/m4/fallocate.m4 \
	$(top_srcdir)/m4/gdlib.m4 $(top_srcdir)/m4/gettext.m4 \
	$(top_srcdir)/m4/glibc21.m4 $(top_srcdir)/m4/iconv.m4 \
	$(top_srcdir)/m4/intdiv0.m4 $(top_srcdir)/m4/inttypes-pri.m4 \
	$(top_srcdir)/m4/inttypes.m4 $(top_srcdir)/m4/inttypes_h.m4 \
	$(top_srcdir)/m4/lcmessage.m4 $(top_srcdir)/m4/lib-ld.m4 \
	$(top_srcdir)/m4/lib-link.m4 $(top_srcdir)/m4/lib-prefix.m4 \
	$(top_srcdir)/m4/libpng.m4 $(top_srcdir)/m4/libupnp.m4 \
	$(top_srcdir)/m4/nls.m4 $(top_srcdir)/m4/pkg.m4 \
	$(top_srcdir)/m4/progtest.m4 $(top_srcdir)/m4/readline.m4 \
	$(top_srcdir)/m4/stdint_h.m4 $(top_srcdir)/m4/uintmax_t.m4 \
	$(top_srcdir)/m4/ulonglong.m4 $(top_srcdir)/m4/wxwin.m4 \
	$(top_srcdir)/m4/zlib.m4 $(top_srcdir)/acinclude.m4 \
	$(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
PROGRAMS = $(noinst_PROGRAMS)
am_mulefileview_OBJECTS = mulefileview-CFile.$(OBJEXT) \
	mulefileview-SafeFile.$(OBJEXT) mulefileview-Tag.$(OBJEXT) \
	mulefileview-UInt128.$(OBJEXT) mulefileview-FileView.$(OBJEXT) \
	mulefileview-KadFiles.$(OBJEXT) mulefileview-Print.$(OBJEXT)
mulefileview_OBJECTS = $(am_mulefileview_OBJECTS)
am__DEPENDENCIES_1 =
DEFAULT_INCLUDES = -I. -I$(srcdir) -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(mulefileview_SOURCES)
DIST_SOURCES = $(mulefileview_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run aclocal-1.9
ALCC_FALSE = 
ALCC_MANPAGES = 
ALCC_TRUE = #
ALC_FALSE = 
ALC_MANPAGES = 
ALC_TRUE = #
ALLOCA = 
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run tar
AMULECMD_MANPAGES = 
AMULEWEB_DEFS = -DWITH_LIBPNG
AMULE_DAEMON_FALSE = #
AMULE_DAEMON_MANPAGES = 
AMULE_DAEMON_TRUE = 
AMULE_GUI_FALSE = 
AMULE_GUI_MANPAGES = 
AMULE_GUI_TRUE = #
AR = arm-mv5sft-linux-gnueabi-ar
AUTOCONF = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run autoconf
AUTOHEADER = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run autoheader
AUTOMAKE = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run automake-1.9
AWK = gawk
BFD_CPPFLAGS = 
BFD_LIBS = 
BUILD_CC = gcc
BUILD_CFLAGS = 
BUILD_CPPFLAGS = 
BUILD_EXEEXT = 
BUILD_INCLUDED_LIBINTL = no
BUILD_LDFLAGS = 
CAS_DEFS = 
CAS_FALSE = 
CAS_MANPAGES = 
CAS_TRUE = #
CATOBJEXT = .gmo
CC = arm-mv5sft-linux-gnueabi-gcc
CCDEPMODE = depmode=gcc3
CFLAGS = 
COMPILE_CMD_FALSE = 
COMPILE_CMD_TRUE = #
COMPILE_NLS_FALSE = 
COMPILE_NLS_TRUE = #
CPP = arm-mv5sft-linux-gnueabi-gcc -E
CPPFLAGS = -I/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../include
CRYPTOPP_CPPFLAGS =  -D__WEAK_CRYPTO__
CRYPTOPP_LDFLAGS = 
CRYPTOPP_LIBS = /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../cryptopp552/libcryptopp.a
CXX = arm-mv5sft-linux-gnueabi-g++
CXXCPP = arm-mv5sft-linux-gnueabi-g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = 
CYGPATH_W = echo
DATADIRNAME = share
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
ED2K_FALSE = #
ED2K_MANPAGES = 
ED2K_TRUE = 
EGREP = grep -E
ENABLE_IP2COUNTRY_FALSE = 
ENABLE_IP2COUNTRY_TRUE = #
ENABLE_UPNP_FALSE = 
ENABLE_UPNP_TRUE = #
EXEEXT = 
GDLIB_CFLAGS = 
GDLIB_CONFIG_PATH = 
GDLIB_LDFLAGS = 
GDLIB_LIBS = 
GENCAT = gencat
GENERATE_FLEX_HEADER_FALSE = 
GENERATE_FLEX_HEADER_TRUE = #
GEOIP_CPPFLAGS = 
GEOIP_LDFLAGS = 
GEOIP_LIBS = 
GLIBC21 = yes
GMSGFMT = :
INCINTL = 
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_SKINS_FALSE = 
INSTALL_SKINS_TRUE = #
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
INSTOBJEXT = .mo
INTLBISON = :
INTLLIBS = 
INTLOBJS = 
INTL_LIBTOOL_SUFFIX_PREFIX = 
LD = arm-mv5sft-linux-gnueabi-ld
LDFLAGS = -L/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../lib
LEX = :
LEXLIB = -lfl
LEX_OUTPUT_ROOT = 
LIBICONV = /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../lib/libiconv.so -Wl,-rpath -Wl,/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../lib
LIBINTL = 
LIBOBJS =  lstat$U.o memcmp$U.o stat$U.o strtod$U.o
LIBPNG_CFLAGS = -I/usr/local/include/libpng12
LIBPNG_CONFIG_PATH = ../libpng-1.2.39/libpng-config
LIBPNG_LDFLAGS = -L/usr/local/lib
LIBPNG_LIBS = -lpng12
LIBS = 
LIBUPNP_CFLAGS = 
LIBUPNP_CPPFLAGS = 
LIBUPNP_LDFLAGS = 
LIBUPNP_LIBS = 
LTLIBICONV = -L/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../lib -liconv -R/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../lib
LTLIBINTL = 
LTLIBOBJS =  lstat$U.lo memcmp$U.lo stat$U.lo strtod$U.lo
MAINT = #
MAINTAINER_MODE_FALSE = 
MAINTAINER_MODE_TRUE = #
MAKEINFO = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run makeinfo
MKINSTALLDIRS = ./mkinstalldirs
MONOLITHIC_FALSE = 
MONOLITHIC_MANPAGES = 
MONOLITHIC_TRUE = #
MSGFMT = :
MSGMERGE = :
MULECFLAGS = -w  -g -ggdb -fno-inline -fmessage-length=0
MULECPPFLAGS =  -D__DEBUG__ -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -DUSE_WX_EXTENSIONS
MULECXXFLAGS = -w  -g -ggdb -fno-inline -fmessage-length=0
MULELDFLAGS =  -lpthread
MULERCFLAGS = 
NEED_CORESERVICES_FALSE = 
NEED_CORESERVICES_TRUE = #
NEED_RC_FALSE = 
NEED_RC_TRUE = #
OBJEXT = o
PACKAGE = amule
PACKAGE_BUGREPORT = admin@amule.org
PACKAGE_NAME = aMule
PACKAGE_STRING = aMule 2.2.6
PACKAGE_TARNAME = amule
PACKAGE_VERSION = 2.2.6
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
POSUB = po
POW_LIB = -lm
RANLIB = arm-mv5sft-linux-gnueabi-ranlib
RC = 
RCFLAGS = 
READLINE_LIBS = 
REGEX_LIBS = 
RESOLV_LIB = 
SET_MAKE = 
SHELL = /bin/sh
STRIP = arm-mv5sft-linux-gnueabi-strip
SVNDATE = 
SYS_WIN32_FALSE = 
SYS_WIN32_TRUE = #
USE_INCLUDED_LIBINTL = no
USE_NLS = no
VERSION = 2.2.6
WEB_FALSE = #
WEB_MANPAGES = 
WEB_TRUE = 
WXBASE_CPPFLAGS = -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib/wx/include/arm-mv5sft-linux-gnueabi-base-unicode-release-2.8 -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/include -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/contrib/include -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DwxUSE_GUI=0 -DwxUSE_GUI=0
WXBASE_LIBS = -L/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib -pthread   -Wl,-rpath,/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib -lwx_baseu_net-2.8-arm-mv5sft-linux-gnueabi -lwx_baseu-2.8-arm-mv5sft-linux-gnueabi 
WXCAS_FALSE = 
WXCAS_MANPAGES = 
WXCAS_TRUE = #
WX_CFLAGS = -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib/wx/include/arm-mv5sft-linux-gnueabi-base-unicode-release-2.8 -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/include -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/contrib/include -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DwxUSE_GUI=0 -pthread
WX_CFLAGS_ONLY = -pthread
WX_CONFIG_PATH = ../wxWidgets-2.8.9/wx-config
WX_CPPFLAGS = -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib/wx/include/arm-mv5sft-linux-gnueabi-base-unicode-release-2.8 -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/include -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/contrib/include -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DwxUSE_GUI=0
WX_CXXFLAGS = -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib/wx/include/arm-mv5sft-linux-gnueabi-base-unicode-release-2.8 -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/include -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/contrib/include -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DwxUSE_GUI=0 -pthread
WX_CXXFLAGS_ONLY = 
WX_DEBUG = 0
WX_LIBS = -L/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib -pthread   -Wl,-rpath,/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib -lwx_baseu_adv-2.8-arm-mv5sft-linux-gnueabi -lwx_baseu_core-2.8-arm-mv5sft-linux-gnueabi -lwx_baseu_net-2.8-arm-mv5sft-linux-gnueabi -lwx_baseu-2.8-arm-mv5sft-linux-gnueabi 
WX_LIBS_STATIC = 
WX_PORT = base
WX_RESCOMP = 
WX_SHARED = 1
WX_UNICODE = 
WX_VERSION_FULL = 2.8.9
WX_VERSION_MAJOR = 2
WX_VERSION_MINOR = 8
X11LIBS = 
XGETTEXT = :
YACC = yacc
ZLIB_CPPFLAGS = -I/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/..//include
ZLIB_LDFLAGS = -L/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/..//lib
ZLIB_LIBS = -lz
ac_ct_AR = 
ac_ct_BUILD_CC = gcc
ac_ct_CC = 
ac_ct_CXX = 
ac_ct_LD = 
ac_ct_RANLIB = 
ac_ct_RC = 
ac_ct_STRIP = 
ac_pt_PKG_CONFIG = /usr/bin/pkg-config
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__fastdepCXX_FALSE = #
am__fastdepCXX_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
datadir = ${prefix}/share
docdir = ${prefix}/share/doc/aMule-2.2.6
exec_prefix = ${prefix}
host = arm-mv5sft-linux-gnueabi
host_alias = arm-mv5sft-linux-gnueabi
host_cpu = arm
host_os = linux-gnueabi
host_vendor = mv5sft
includedir = ${prefix}/include
infodir = ${prefix}/info
install_sh = /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
mkdir_p = mkdir -p --
oldincludedir = /usr/include
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 
mulefileview_SOURCES = \
	../../CFile.cpp \
	../../SafeFile.cpp \
	../../Tag.cpp \
	../../kademlia/utils/UInt128.cpp \
	FileView.cpp \
	KadFiles.h \
	KadFiles.cpp \
	Print.h \
	Print.cpp
mulefileview_DEPENDENCIES = ../../libs/common/libmulecommon.a
mulefileview_CPPFLAGS = $(MULECPPFLAGS) -I$(top_srcdir)/src/libs -I$(top_srcdir)/src/include $(WXBASE_CPPFLAGS) $(CRYPTOPP_CPPFLAGS)
mulefileview_CXXFLAGS = $(MULECXXFLAGS) $(WX_CFLAGS_ONLY) $(WX_CXXFLAGS_ONLY)
mulefileview_LDFLAGS = $(MULELDFLAGS) -L../../libs/common $(CRYPTOPP_LDFLAGS)
mulefileview_LDADD = -lmulecommon $(WXBASE_LIBS) $(CRYPTOPP_LIBS)
all: all-am
.SUFFIXES:
.SUFFIXES: .cpp .o .obj
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  src/utils/fileview/Makefile'>/dev/null; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  src/utils/fileview/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'>/dev/null; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe) denoiser;; \
	esac;
$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(top_srcdir)/configure: # $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
mulefileview$(EXEEXT): $(mulefileview_OBJECTS) $(mulefileview_DEPENDENCIES) 
	echo "Linking $(@F)"
	@rm -f mulefileview$(EXEEXT)
	$(CXXLINK) $(mulefileview_LDFLAGS) $(mulefileview_OBJECTS) $(mulefileview_LDADD) $(LIBS)
mostlyclean-compile:
	-rm -f *.$(OBJEXT)
distclean-compile:
	-rm -f *.tab.c
include ./$(DEPDIR)/mulefileview-CFile.Po
include ./$(DEPDIR)/mulefileview-FileView.Po
include ./$(DEPDIR)/mulefileview-KadFiles.Po
include ./$(DEPDIR)/mulefileview-Print.Po
include ./$(DEPDIR)/mulefileview-SafeFile.Po
include ./$(DEPDIR)/mulefileview-Tag.Po
include ./$(DEPDIR)/mulefileview-UInt128.Po
.cpp.o:
	echo "Compiling $(<F)"
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
.cpp.obj:
	echo "Compiling $(<F)"
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ `$(CYGPATH_W) '$<'`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
mulefileview-CFile.o: ../../CFile.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-CFile.o -MD -MP -MF "$(DEPDIR)/mulefileview-CFile.Tpo" -c -o mulefileview-CFile.o `test -f '../../CFile.cpp' || echo '$(srcdir)/'`../../CFile.cpp; \
	then mv -f "$(DEPDIR)/mulefileview-CFile.Tpo" "$(DEPDIR)/mulefileview-CFile.Po"; else rm -f "$(DEPDIR)/mulefileview-CFile.Tpo"; exit 1; fi
mulefileview-CFile.obj: ../../CFile.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-CFile.obj -MD -MP -MF "$(DEPDIR)/mulefileview-CFile.Tpo" -c -o mulefileview-CFile.obj `if test -f '../../CFile.cpp'; then $(CYGPATH_W) '../../CFile.cpp'; else $(CYGPATH_W) '$(srcdir)/../../CFile.cpp'; fi`; \
	then mv -f "$(DEPDIR)/mulefileview-CFile.Tpo" "$(DEPDIR)/mulefileview-CFile.Po"; else rm -f "$(DEPDIR)/mulefileview-CFile.Tpo"; exit 1; fi
mulefileview-SafeFile.o: ../../SafeFile.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-SafeFile.o -MD -MP -MF "$(DEPDIR)/mulefileview-SafeFile.Tpo" -c -o mulefileview-SafeFile.o `test -f '../../SafeFile.cpp' || echo '$(srcdir)/'`../../SafeFile.cpp; \
	then mv -f "$(DEPDIR)/mulefileview-SafeFile.Tpo" "$(DEPDIR)/mulefileview-SafeFile.Po"; else rm -f "$(DEPDIR)/mulefileview-SafeFile.Tpo"; exit 1; fi
mulefileview-SafeFile.obj: ../../SafeFile.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-SafeFile.obj -MD -MP -MF "$(DEPDIR)/mulefileview-SafeFile.Tpo" -c -o mulefileview-SafeFile.obj `if test -f '../../SafeFile.cpp'; then $(CYGPATH_W) '../../SafeFile.cpp'; else $(CYGPATH_W) '$(srcdir)/../../SafeFile.cpp'; fi`; \
	then mv -f "$(DEPDIR)/mulefileview-SafeFile.Tpo" "$(DEPDIR)/mulefileview-SafeFile.Po"; else rm -f "$(DEPDIR)/mulefileview-SafeFile.Tpo"; exit 1; fi
mulefileview-Tag.o: ../../Tag.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-Tag.o -MD -MP -MF "$(DEPDIR)/mulefileview-Tag.Tpo" -c -o mulefileview-Tag.o `test -f '../../Tag.cpp' || echo '$(srcdir)/'`../../Tag.cpp; \
	then mv -f "$(DEPDIR)/mulefileview-Tag.Tpo" "$(DEPDIR)/mulefileview-Tag.Po"; else rm -f "$(DEPDIR)/mulefileview-Tag.Tpo"; exit 1; fi
mulefileview-Tag.obj: ../../Tag.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-Tag.obj -MD -MP -MF "$(DEPDIR)/mulefileview-Tag.Tpo" -c -o mulefileview-Tag.obj `if test -f '../../Tag.cpp'; then $(CYGPATH_W) '../../Tag.cpp'; else $(CYGPATH_W) '$(srcdir)/../../Tag.cpp'; fi`; \
	then mv -f "$(DEPDIR)/mulefileview-Tag.Tpo" "$(DEPDIR)/mulefileview-Tag.Po"; else rm -f "$(DEPDIR)/mulefileview-Tag.Tpo"; exit 1; fi
mulefileview-UInt128.o: ../../kademlia/utils/UInt128.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-UInt128.o -MD -MP -MF "$(DEPDIR)/mulefileview-UInt128.Tpo" -c -o mulefileview-UInt128.o `test -f '../../kademlia/utils/UInt128.cpp' || echo '$(srcdir)/'`../../kademlia/utils/UInt128.cpp; \
	then mv -f "$(DEPDIR)/mulefileview-UInt128.Tpo" "$(DEPDIR)/mulefileview-UInt128.Po"; else rm -f "$(DEPDIR)/mulefileview-UInt128.Tpo"; exit 1; fi
mulefileview-UInt128.obj: ../../kademlia/utils/UInt128.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-UInt128.obj -MD -MP -MF "$(DEPDIR)/mulefileview-UInt128.Tpo" -c -o mulefileview-UInt128.obj `if test -f '../../kademlia/utils/UInt128.cpp'; then $(CYGPATH_W) '../../kademlia/utils/UInt128.cpp'; else $(CYGPATH_W) '$(srcdir)/../../kademlia/utils/UInt128.cpp'; fi`; \
	then mv -f "$(DEPDIR)/mulefileview-UInt128.Tpo" "$(DEPDIR)/mulefileview-UInt128.Po"; else rm -f "$(DEPDIR)/mulefileview-UInt128.Tpo"; exit 1; fi
mulefileview-FileView.o: FileView.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-FileView.o -MD -MP -MF "$(DEPDIR)/mulefileview-FileView.Tpo" -c -o mulefileview-FileView.o `test -f 'FileView.cpp' || echo '$(srcdir)/'`FileView.cpp; \
	then mv -f "$(DEPDIR)/mulefileview-FileView.Tpo" "$(DEPDIR)/mulefileview-FileView.Po"; else rm -f "$(DEPDIR)/mulefileview-FileView.Tpo"; exit 1; fi
mulefileview-FileView.obj: FileView.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-FileView.obj -MD -MP -MF "$(DEPDIR)/mulefileview-FileView.Tpo" -c -o mulefileview-FileView.obj `if test -f 'FileView.cpp'; then $(CYGPATH_W) 'FileView.cpp'; else $(CYGPATH_W) '$(srcdir)/FileView.cpp'; fi`; \
	then mv -f "$(DEPDIR)/mulefileview-FileView.Tpo" "$(DEPDIR)/mulefileview-FileView.Po"; else rm -f "$(DEPDIR)/mulefileview-FileView.Tpo"; exit 1; fi
mulefileview-KadFiles.o: KadFiles.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-KadFiles.o -MD -MP -MF "$(DEPDIR)/mulefileview-KadFiles.Tpo" -c -o mulefileview-KadFiles.o `test -f 'KadFiles.cpp' || echo '$(srcdir)/'`KadFiles.cpp; \
	then mv -f "$(DEPDIR)/mulefileview-KadFiles.Tpo" "$(DEPDIR)/mulefileview-KadFiles.Po"; else rm -f "$(DEPDIR)/mulefileview-KadFiles.Tpo"; exit 1; fi
mulefileview-KadFiles.obj: KadFiles.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-KadFiles.obj -MD -MP -MF "$(DEPDIR)/mulefileview-KadFiles.Tpo" -c -o mulefileview-KadFiles.obj `if test -f 'KadFiles.cpp'; then $(CYGPATH_W) 'KadFiles.cpp'; else $(CYGPATH_W) '$(srcdir)/KadFiles.cpp'; fi`; \
	then mv -f "$(DEPDIR)/mulefileview-KadFiles.Tpo" "$(DEPDIR)/mulefileview-KadFiles.Po"; else rm -f "$(DEPDIR)/mulefileview-KadFiles.Tpo"; exit 1; fi
mulefileview-Print.o: Print.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-Print.o -MD -MP -MF "$(DEPDIR)/mulefileview-Print.Tpo" -c -o mulefileview-Print.o `test -f 'Print.cpp' || echo '$(srcdir)/'`Print.cpp; \
	then mv -f "$(DEPDIR)/mulefileview-Print.Tpo" "$(DEPDIR)/mulefileview-Print.Po"; else rm -f "$(DEPDIR)/mulefileview-Print.Tpo"; exit 1; fi
mulefileview-Print.obj: Print.cpp
	echo "Compiling $(<F)"
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mulefileview_CPPFLAGS) $(CPPFLAGS) $(mulefileview_CXXFLAGS) $(CXXFLAGS) -MT mulefileview-Print.obj -MD -MP -MF "$(DEPDIR)/mulefileview-Print.Tpo" -c -o mulefileview-Print.obj `if test -f 'Print.cpp'; then $(CYGPATH_W) 'Print.cpp'; else $(CYGPATH_W) '$(srcdir)/Print.cpp'; fi`; \
	then mv -f "$(DEPDIR)/mulefileview-Print.Tpo" "$(DEPDIR)/mulefileview-Print.Po"; else rm -f "$(DEPDIR)/mulefileview-Print.Tpo"; exit 1; fi
uninstall-info-am:
ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS
TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique
GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here
distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am
install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:
clean-generic:
distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am
clean-am: clean-generic clean-noinstPROGRAMS mostlyclean-am
distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags
dvi: dvi-am
dvi-am:
html: html-am
info: info-am
info-am:
install-data-am:
install-exec-am:
install-info: install-info-am
install-man:
installcheck-am:
maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic
mostlyclean: mostlyclean-am
mostlyclean-am: mostlyclean-compile mostlyclean-generic
pdf: pdf-am
pdf-am:
ps: ps-am
ps-am:
uninstall-am: uninstall-info-am
.PHONY: CTAGS GTAGS all all-am check check-am clean clean-generic \
	clean-noinstPROGRAMS ctags distclean distclean-compile \
	distclean-generic distclean-tags distdir dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-exec install-exec-am install-info \
	install-info-am install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-info-am
.NOEXPORT:
