# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:26 jack Exp $

COMMON=	dbc_class.html \
	dbc_close.html \
	dbc_count.html \
	dbc_del.html \
	dbc_dup.html \
	dbc_get.html \
	dbc_list.html \
	dbc_put.html \
	dbc_set_priority.html
