# $Id: Makefile,v 1.1.1.1 2009/10/09 03:04:05 jack Exp $

COPY=	solaris.txt
BUILD=  appsignals.html cache.html compatible.html copy.html \
	environ.html errorret.html faq.html mt.html namespace.html \
	ram.html runtime.html scope.html

all: ${BUILD}
