# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:22 jack Exp $

BUILD=  create.html db_config.html encrypt.html error.html faq.html \
	intro.html naming.html open.html region.html remote.html \
	security.html

all: ${BUILD}
