# $Id: Makefile,v 1.1.1.1 2009/10/09 03:04:07 jack Exp $

BUILD=  app.html base_meth.html bulk.html clock_skew.html comm.html \
	elect.html ex.html ex_comm.html ex_rq.html faq.html id.html \
	init.html intro.html lease.html mastersync.html mgr_meth.html \
	newsite.html partition.html pri.html trans.html

all: ${BUILD}
