/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "db_config.h"
#include "db_server.h"

bool_t
xdr___env_create_msg (XDR *xdrs, __env_create_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->timeout))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_create_reply (XDR *xdrs, __env_create_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->envcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_cdsgroup_begin_msg (XDR *xdrs, __env_cdsgroup_begin_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_cdsgroup_begin_reply (XDR *xdrs, __env_cdsgroup_begin_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnidcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_close_msg (XDR *xdrs, __env_close_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_close_reply (XDR *xdrs, __env_close_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_dbremove_msg (XDR *xdrs, __env_dbremove_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->subdb, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_dbremove_reply (XDR *xdrs, __env_dbremove_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_dbrename_msg (XDR *xdrs, __env_dbrename_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->subdb, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->newname, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_dbrename_reply (XDR *xdrs, __env_dbrename_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_get_cachesize_msg (XDR *xdrs, __env_get_cachesize_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_get_cachesize_reply (XDR *xdrs, __env_get_cachesize_reply *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->status))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->gbytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->bytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->ncache))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->status);
			IXDR_PUT_U_LONG(buf, objp->gbytes);
			IXDR_PUT_U_LONG(buf, objp->bytes);
			IXDR_PUT_U_LONG(buf, objp->ncache);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->status))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->gbytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->bytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->ncache))
				 return FALSE;
		} else {
			objp->status = IXDR_GET_LONG(buf);
			objp->gbytes = IXDR_GET_U_LONG(buf);
			objp->bytes = IXDR_GET_U_LONG(buf);
			objp->ncache = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->gbytes))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->bytes))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->ncache))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_get_encrypt_flags_msg (XDR *xdrs, __env_get_encrypt_flags_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_get_encrypt_flags_reply (XDR *xdrs, __env_get_encrypt_flags_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_get_flags_msg (XDR *xdrs, __env_get_flags_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_get_flags_reply (XDR *xdrs, __env_get_flags_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_get_home_msg (XDR *xdrs, __env_get_home_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_get_home_reply (XDR *xdrs, __env_get_home_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->home, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_get_open_flags_msg (XDR *xdrs, __env_get_open_flags_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_get_open_flags_reply (XDR *xdrs, __env_get_open_flags_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_open_msg (XDR *xdrs, __env_open_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->home, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_open_reply (XDR *xdrs, __env_open_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->envcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_remove_msg (XDR *xdrs, __env_remove_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->home, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_remove_reply (XDR *xdrs, __env_remove_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_set_cachesize_msg (XDR *xdrs, __env_set_cachesize_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->gbytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->bytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->ncache))
				 return FALSE;
		} else {
			IXDR_PUT_U_LONG(buf, objp->dbenvcl_id);
			IXDR_PUT_U_LONG(buf, objp->gbytes);
			IXDR_PUT_U_LONG(buf, objp->bytes);
			IXDR_PUT_U_LONG(buf, objp->ncache);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->gbytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->bytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->ncache))
				 return FALSE;
		} else {
			objp->dbenvcl_id = IXDR_GET_U_LONG(buf);
			objp->gbytes = IXDR_GET_U_LONG(buf);
			objp->bytes = IXDR_GET_U_LONG(buf);
			objp->ncache = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->gbytes))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->bytes))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->ncache))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_set_cachesize_reply (XDR *xdrs, __env_set_cachesize_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_set_encrypt_msg (XDR *xdrs, __env_set_encrypt_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->passwd, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_set_encrypt_reply (XDR *xdrs, __env_set_encrypt_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_set_flags_msg (XDR *xdrs, __env_set_flags_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->onoff))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_set_flags_reply (XDR *xdrs, __env_set_flags_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_txn_begin_msg (XDR *xdrs, __env_txn_begin_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->parentcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_txn_begin_reply (XDR *xdrs, __env_txn_begin_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnidcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_txn_recover_msg (XDR *xdrs, __env_txn_recover_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->count))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_txn_recover_reply (XDR *xdrs, __env_txn_recover_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->txn.txn_val, (u_int *) &objp->txn.txn_len, ~0,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->gid.gid_val, (u_int *) &objp->gid.gid_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->retcount))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_create_msg (XDR *xdrs, __db_create_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_create_reply (XDR *xdrs, __db_create_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dbcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_associate_msg (XDR *xdrs, __db_associate_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->sdbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->flags))
				 return FALSE;
		} else {
			IXDR_PUT_U_LONG(buf, objp->dbpcl_id);
			IXDR_PUT_U_LONG(buf, objp->txnpcl_id);
			IXDR_PUT_U_LONG(buf, objp->sdbpcl_id);
			IXDR_PUT_U_LONG(buf, objp->flags);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->sdbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->flags))
				 return FALSE;
		} else {
			objp->dbpcl_id = IXDR_GET_U_LONG(buf);
			objp->txnpcl_id = IXDR_GET_U_LONG(buf);
			objp->sdbpcl_id = IXDR_GET_U_LONG(buf);
			objp->flags = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->sdbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_associate_reply (XDR *xdrs, __db_associate_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_close_msg (XDR *xdrs, __db_close_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_close_reply (XDR *xdrs, __db_close_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_cursor_msg (XDR *xdrs, __db_cursor_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_cursor_reply (XDR *xdrs, __db_cursor_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dbcidcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_del_msg (XDR *xdrs, __db_del_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbpcl_id);
		IXDR_PUT_U_LONG(buf, objp->txnpcl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyulen);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbpcl_id = IXDR_GET_U_LONG(buf);
		objp->txnpcl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyulen = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_del_reply (XDR *xdrs, __db_del_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_msg (XDR *xdrs, __db_get_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbpcl_id);
		IXDR_PUT_U_LONG(buf, objp->txnpcl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyulen);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->datadlen);
		IXDR_PUT_U_LONG(buf, objp->datadoff);
		IXDR_PUT_U_LONG(buf, objp->dataulen);
		IXDR_PUT_U_LONG(buf, objp->dataflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbpcl_id = IXDR_GET_U_LONG(buf);
		objp->txnpcl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyulen = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		objp->datadlen = IXDR_GET_U_LONG(buf);
		objp->datadoff = IXDR_GET_U_LONG(buf);
		objp->dataulen = IXDR_GET_U_LONG(buf);
		objp->dataflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_reply (XDR *xdrs, __db_get_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_bt_minkey_msg (XDR *xdrs, __db_get_bt_minkey_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_bt_minkey_reply (XDR *xdrs, __db_get_bt_minkey_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->minkey))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_dbname_msg (XDR *xdrs, __db_get_dbname_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_dbname_reply (XDR *xdrs, __db_get_dbname_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filename, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->dbname, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_encrypt_flags_msg (XDR *xdrs, __db_get_encrypt_flags_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_encrypt_flags_reply (XDR *xdrs, __db_get_encrypt_flags_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_flags_msg (XDR *xdrs, __db_get_flags_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_flags_reply (XDR *xdrs, __db_get_flags_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_h_ffactor_msg (XDR *xdrs, __db_get_h_ffactor_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_h_ffactor_reply (XDR *xdrs, __db_get_h_ffactor_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->ffactor))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_h_nelem_msg (XDR *xdrs, __db_get_h_nelem_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_h_nelem_reply (XDR *xdrs, __db_get_h_nelem_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->nelem))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_lorder_msg (XDR *xdrs, __db_get_lorder_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_lorder_reply (XDR *xdrs, __db_get_lorder_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->lorder))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_open_flags_msg (XDR *xdrs, __db_get_open_flags_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_open_flags_reply (XDR *xdrs, __db_get_open_flags_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_pagesize_msg (XDR *xdrs, __db_get_pagesize_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_pagesize_reply (XDR *xdrs, __db_get_pagesize_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pagesize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_priority_msg (XDR *xdrs, __db_get_priority_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_priority_reply (XDR *xdrs, __db_get_priority_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->priority))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_q_extentsize_msg (XDR *xdrs, __db_get_q_extentsize_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_q_extentsize_reply (XDR *xdrs, __db_get_q_extentsize_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->extentsize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_re_delim_msg (XDR *xdrs, __db_get_re_delim_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_re_delim_reply (XDR *xdrs, __db_get_re_delim_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->delim))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_re_len_msg (XDR *xdrs, __db_get_re_len_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_re_len_reply (XDR *xdrs, __db_get_re_len_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->len))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_re_pad_msg (XDR *xdrs, __db_get_re_pad_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_re_pad_reply (XDR *xdrs, __db_get_re_pad_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pad))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_join_msg (XDR *xdrs, __db_join_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->curs.curs_val, (u_int *) &objp->curs.curs_len, ~0,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_join_reply (XDR *xdrs, __db_join_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dbcidcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_key_range_msg (XDR *xdrs, __db_key_range_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbpcl_id);
		IXDR_PUT_U_LONG(buf, objp->txnpcl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyulen);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbpcl_id = IXDR_GET_U_LONG(buf);
		objp->txnpcl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyulen = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_key_range_reply (XDR *xdrs, __db_key_range_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->less))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->equal))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->greater))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_open_msg (XDR *xdrs, __db_open_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->subdb, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_open_reply (XDR *xdrs, __db_open_reply *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->status))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dbcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->type))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->lorder))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->status);
			IXDR_PUT_U_LONG(buf, objp->dbcl_id);
			IXDR_PUT_U_LONG(buf, objp->type);
			IXDR_PUT_U_LONG(buf, objp->lorder);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->status))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dbcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->type))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->lorder))
				 return FALSE;
		} else {
			objp->status = IXDR_GET_LONG(buf);
			objp->dbcl_id = IXDR_GET_U_LONG(buf);
			objp->type = IXDR_GET_U_LONG(buf);
			objp->lorder = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dbcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->lorder))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_pget_msg (XDR *xdrs, __db_pget_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbpcl_id);
		IXDR_PUT_U_LONG(buf, objp->txnpcl_id);
		IXDR_PUT_U_LONG(buf, objp->skeydlen);
		IXDR_PUT_U_LONG(buf, objp->skeydoff);
		IXDR_PUT_U_LONG(buf, objp->skeyulen);
		IXDR_PUT_U_LONG(buf, objp->skeyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->skeydata.skeydata_val, (u_int *) &objp->skeydata.skeydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->pkeydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->pkeydlen);
		IXDR_PUT_U_LONG(buf, objp->pkeydoff);
		IXDR_PUT_U_LONG(buf, objp->pkeyulen);
		IXDR_PUT_U_LONG(buf, objp->pkeyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->pkeydata.pkeydata_val, (u_int *) &objp->pkeydata.pkeydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->datadlen);
		IXDR_PUT_U_LONG(buf, objp->datadoff);
		IXDR_PUT_U_LONG(buf, objp->dataulen);
		IXDR_PUT_U_LONG(buf, objp->dataflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeyflags))
				 return FALSE;

		} else {
		objp->dbpcl_id = IXDR_GET_U_LONG(buf);
		objp->txnpcl_id = IXDR_GET_U_LONG(buf);
		objp->skeydlen = IXDR_GET_U_LONG(buf);
		objp->skeydoff = IXDR_GET_U_LONG(buf);
		objp->skeyulen = IXDR_GET_U_LONG(buf);
		objp->skeyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->skeydata.skeydata_val, (u_int *) &objp->skeydata.skeydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->pkeydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeyflags))
				 return FALSE;

		} else {
		objp->pkeydlen = IXDR_GET_U_LONG(buf);
		objp->pkeydoff = IXDR_GET_U_LONG(buf);
		objp->pkeyulen = IXDR_GET_U_LONG(buf);
		objp->pkeyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->pkeydata.pkeydata_val, (u_int *) &objp->pkeydata.pkeydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		objp->datadlen = IXDR_GET_U_LONG(buf);
		objp->datadoff = IXDR_GET_U_LONG(buf);
		objp->dataulen = IXDR_GET_U_LONG(buf);
		objp->dataflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->skeydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->skeydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->skeyulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->skeyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->skeydata.skeydata_val, (u_int *) &objp->skeydata.skeydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pkeydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pkeydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pkeyulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pkeyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->pkeydata.pkeydata_val, (u_int *) &objp->pkeydata.pkeydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_pget_reply (XDR *xdrs, __db_pget_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->skeydata.skeydata_val, (u_int *) &objp->skeydata.skeydata_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->pkeydata.pkeydata_val, (u_int *) &objp->pkeydata.pkeydata_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_put_msg (XDR *xdrs, __db_put_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbpcl_id);
		IXDR_PUT_U_LONG(buf, objp->txnpcl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyulen);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->datadlen);
		IXDR_PUT_U_LONG(buf, objp->datadoff);
		IXDR_PUT_U_LONG(buf, objp->dataulen);
		IXDR_PUT_U_LONG(buf, objp->dataflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbpcl_id = IXDR_GET_U_LONG(buf);
		objp->txnpcl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyulen = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		objp->datadlen = IXDR_GET_U_LONG(buf);
		objp->datadoff = IXDR_GET_U_LONG(buf);
		objp->dataulen = IXDR_GET_U_LONG(buf);
		objp->dataflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_put_reply (XDR *xdrs, __db_put_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_remove_msg (XDR *xdrs, __db_remove_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->subdb, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_remove_reply (XDR *xdrs, __db_remove_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_rename_msg (XDR *xdrs, __db_rename_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->subdb, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->newname, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_rename_reply (XDR *xdrs, __db_rename_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_bt_minkey_msg (XDR *xdrs, __db_set_bt_minkey_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->minkey))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_bt_minkey_reply (XDR *xdrs, __db_set_bt_minkey_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_encrypt_msg (XDR *xdrs, __db_set_encrypt_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->passwd, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_encrypt_reply (XDR *xdrs, __db_set_encrypt_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_flags_msg (XDR *xdrs, __db_set_flags_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_flags_reply (XDR *xdrs, __db_set_flags_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_h_ffactor_msg (XDR *xdrs, __db_set_h_ffactor_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->ffactor))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_h_ffactor_reply (XDR *xdrs, __db_set_h_ffactor_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_h_nelem_msg (XDR *xdrs, __db_set_h_nelem_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->nelem))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_h_nelem_reply (XDR *xdrs, __db_set_h_nelem_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_lorder_msg (XDR *xdrs, __db_set_lorder_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->lorder))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_lorder_reply (XDR *xdrs, __db_set_lorder_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_pagesize_msg (XDR *xdrs, __db_set_pagesize_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pagesize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_pagesize_reply (XDR *xdrs, __db_set_pagesize_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_priority_msg (XDR *xdrs, __db_set_priority_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->priority))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_priority_reply (XDR *xdrs, __db_set_priority_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_q_extentsize_msg (XDR *xdrs, __db_set_q_extentsize_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->extentsize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_q_extentsize_reply (XDR *xdrs, __db_set_q_extentsize_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_re_delim_msg (XDR *xdrs, __db_set_re_delim_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->delim))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_re_delim_reply (XDR *xdrs, __db_set_re_delim_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_re_len_msg (XDR *xdrs, __db_set_re_len_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->len))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_re_len_reply (XDR *xdrs, __db_set_re_len_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_re_pad_msg (XDR *xdrs, __db_set_re_pad_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pad))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_set_re_pad_reply (XDR *xdrs, __db_set_re_pad_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_stat_msg (XDR *xdrs, __db_stat_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_stat_reply (XDR *xdrs, __db_stat_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->stats.stats_val, (u_int *) &objp->stats.stats_len, ~0,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_sync_msg (XDR *xdrs, __db_sync_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_sync_reply (XDR *xdrs, __db_sync_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_truncate_msg (XDR *xdrs, __db_truncate_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_truncate_reply (XDR *xdrs, __db_truncate_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_close_msg (XDR *xdrs, __dbc_close_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_close_reply (XDR *xdrs, __dbc_close_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_count_msg (XDR *xdrs, __dbc_count_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_count_reply (XDR *xdrs, __dbc_count_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dupcount))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_del_msg (XDR *xdrs, __dbc_del_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_del_reply (XDR *xdrs, __dbc_del_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_dup_msg (XDR *xdrs, __dbc_dup_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_dup_reply (XDR *xdrs, __dbc_dup_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dbcidcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_get_msg (XDR *xdrs, __dbc_get_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbccl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbccl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyulen);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->datadlen);
		IXDR_PUT_U_LONG(buf, objp->datadoff);
		IXDR_PUT_U_LONG(buf, objp->dataulen);
		IXDR_PUT_U_LONG(buf, objp->dataflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbccl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbccl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyulen = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		objp->datadlen = IXDR_GET_U_LONG(buf);
		objp->datadoff = IXDR_GET_U_LONG(buf);
		objp->dataulen = IXDR_GET_U_LONG(buf);
		objp->dataflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_get_reply (XDR *xdrs, __dbc_get_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_get_priority_msg (XDR *xdrs, __dbc_get_priority_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_get_priority_reply (XDR *xdrs, __dbc_get_priority_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->priority))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_pget_msg (XDR *xdrs, __dbc_pget_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbccl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbccl_id);
		IXDR_PUT_U_LONG(buf, objp->skeydlen);
		IXDR_PUT_U_LONG(buf, objp->skeydoff);
		IXDR_PUT_U_LONG(buf, objp->skeyulen);
		IXDR_PUT_U_LONG(buf, objp->skeyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->skeydata.skeydata_val, (u_int *) &objp->skeydata.skeydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->pkeydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->pkeydlen);
		IXDR_PUT_U_LONG(buf, objp->pkeydoff);
		IXDR_PUT_U_LONG(buf, objp->pkeyulen);
		IXDR_PUT_U_LONG(buf, objp->pkeyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->pkeydata.pkeydata_val, (u_int *) &objp->pkeydata.pkeydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->datadlen);
		IXDR_PUT_U_LONG(buf, objp->datadoff);
		IXDR_PUT_U_LONG(buf, objp->dataulen);
		IXDR_PUT_U_LONG(buf, objp->dataflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbccl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->skeyflags))
				 return FALSE;

		} else {
		objp->dbccl_id = IXDR_GET_U_LONG(buf);
		objp->skeydlen = IXDR_GET_U_LONG(buf);
		objp->skeydoff = IXDR_GET_U_LONG(buf);
		objp->skeyulen = IXDR_GET_U_LONG(buf);
		objp->skeyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->skeydata.skeydata_val, (u_int *) &objp->skeydata.skeydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->pkeydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->pkeyflags))
				 return FALSE;

		} else {
		objp->pkeydlen = IXDR_GET_U_LONG(buf);
		objp->pkeydoff = IXDR_GET_U_LONG(buf);
		objp->pkeyulen = IXDR_GET_U_LONG(buf);
		objp->pkeyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->pkeydata.pkeydata_val, (u_int *) &objp->pkeydata.pkeydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		objp->datadlen = IXDR_GET_U_LONG(buf);
		objp->datadoff = IXDR_GET_U_LONG(buf);
		objp->dataulen = IXDR_GET_U_LONG(buf);
		objp->dataflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->skeydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->skeydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->skeyulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->skeyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->skeydata.skeydata_val, (u_int *) &objp->skeydata.skeydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pkeydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pkeydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pkeyulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pkeyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->pkeydata.pkeydata_val, (u_int *) &objp->pkeydata.pkeydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_pget_reply (XDR *xdrs, __dbc_pget_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->skeydata.skeydata_val, (u_int *) &objp->skeydata.skeydata_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->pkeydata.pkeydata_val, (u_int *) &objp->pkeydata.pkeydata_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_put_msg (XDR *xdrs, __dbc_put_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbccl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbccl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyulen);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->datadlen);
		IXDR_PUT_U_LONG(buf, objp->datadoff);
		IXDR_PUT_U_LONG(buf, objp->dataulen);
		IXDR_PUT_U_LONG(buf, objp->dataflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbccl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbccl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyulen = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataulen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		objp->datadlen = IXDR_GET_U_LONG(buf);
		objp->datadoff = IXDR_GET_U_LONG(buf);
		objp->dataulen = IXDR_GET_U_LONG(buf);
		objp->dataflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataulen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_put_reply (XDR *xdrs, __dbc_put_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_set_priority_msg (XDR *xdrs, __dbc_set_priority_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->priority))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_set_priority_reply (XDR *xdrs, __dbc_set_priority_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_abort_msg (XDR *xdrs, __txn_abort_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_abort_reply (XDR *xdrs, __txn_abort_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_commit_msg (XDR *xdrs, __txn_commit_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_commit_reply (XDR *xdrs, __txn_commit_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_discard_msg (XDR *xdrs, __txn_discard_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_discard_reply (XDR *xdrs, __txn_discard_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_prepare_msg (XDR *xdrs, __txn_prepare_msg *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->gid, 128))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_prepare_reply (XDR *xdrs, __txn_prepare_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}
