--- #YAML:1.0
name:               Image-Scale
version:            0.08
abstract:           Fast, high-quality fixed-point image resizing
author:
    - Andy Grundman <andy@hybridized.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::NoWarnings:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
