# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:24 jack Exp $

BUILD=  aix.html conf.html flags.html freebsd.html hpux.html install.html \
	intro.html irix.html linux.html macosx.html notes.html osf1.html \
	qnx.html sco.html shlib.html small.html solaris.html sunos.html \
	test.html ultrix.html

all: ${BUILD}
