# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:24 jack Exp $

BUILD=  cput.html disk.html enomem.html err.html fileopen.html intro.html \
	java.html log.html repl.html rtc.html stat.html toc.html verb.html

all: ${BUILD}
