# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:21 jack Exp $

COMMON=	env_set_lg_bsize.html \
	env_set_lg_dir.html \
	env_set_lg_max.html \
	env_set_lg_mode.html \
	env_set_lg_regionmax.html \
	log_archive.html \
	log_compare.html \
	log_cursor.html \
	log_file.html \
	log_flush.html \
	log_list.html \
	log_printf.html \
	log_put.html \
	log_stat.html \
	logc_class.html \
	logc_close.html \
	logc_get.html \
	lsn_class.html
