# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:25 jack Exp $

BUILD=  btstat.html config.html disk.html dup.html env.html intro.html \
	log_register.html logalloc.html memp_register.html put.html \
	set_feedback.html set_paniccall.html set_tx_recover.html \
	sysmem.html tcl.html toc.html tmp.html txn_check.html

all: ${BUILD}
