#!/bin/sh
set -e
rm -f aclocal.m4 libtool config.cache config.status
libtoolize -c --force
aclocal
perl -spi.bak -e '
	if(/--disable-nls.*Native/){s/--disable/--enable/; s/do not //;}
	s/, USE_NLS=yes/, USE_NLS=no/; ' aclocal.m4
autoconf
autoheader
