#!/bin/sh
if [ -d /usr/share/man ] ; then
	mandir="--mandir=/usr/share/man"
fi
sh ./configure -q --prefix=/usr --sysconfdir=/etc $mandir --disable-shared \
# --with-ldopts="-L/usr/local/lib" --with-cppopts="-I/usr/local/include" \
# --enable-kerberos --enable-mit_kerberos4 \
# --enable-nls --with-included-gettext
#	--with-chooser_routine=test_chooser  --with-user_objs=user_objs.o  --with-user_include=user_objs.h
