MAKEFLAGS=-s --no-print-directory
srcdir = .
top_srcdir = ../../..
pkgdatadir = $(datadir)/amule
pkglibdir = $(libdir)/amule
pkgincludedir = $(includedir)/amule
top_builddir = ../../..
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = arm-mv5sft-linux-gnueabi
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(top_srcdir)/automake/dist-hook.am
subdir = src/libs/ec
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/GeoIP.m4 \
	$(top_srcdir)/m4/build-tools.m4 $(top_srcdir)/m4/codeset.m4 \
	$(top_srcdir)/m4/cryptopp.m4 $(top_srcdir)/m4/fallocate.m4 \
	$(top_srcdir)/m4/gdlib.m4 $(top_srcdir)/m4/gettext.m4 \
	$(top_srcdir)/m4/glibc21.m4 $(top_srcdir)/m4/iconv.m4 \
	$(top_srcdir)/m4/intdiv0.m4 $(top_srcdir)/m4/inttypes-pri.m4 \
	$(top_srcdir)/m4/inttypes.m4 $(top_srcdir)/m4/inttypes_h.m4 \
	$(top_srcdir)/m4/lcmessage.m4 $(top_srcdir)/m4/lib-ld.m4 \
	$(top_srcdir)/m4/lib-link.m4 $(top_srcdir)/m4/lib-prefix.m4 \
	$(top_srcdir)/m4/libpng.m4 $(top_srcdir)/m4/libupnp.m4 \
	$(top_srcdir)/m4/nls.m4 $(top_srcdir)/m4/pkg.m4 \
	$(top_srcdir)/m4/progtest.m4 $(top_srcdir)/m4/readline.m4 \
	$(top_srcdir)/m4/stdint_h.m4 $(top_srcdir)/m4/uintmax_t.m4 \
	$(top_srcdir)/m4/ulonglong.m4 $(top_srcdir)/m4/wxwin.m4 \
	$(top_srcdir)/m4/zlib.m4 $(top_srcdir)/acinclude.m4 \
	$(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-exec-recursive install-info-recursive \
	install-recursive installcheck-recursive installdirs-recursive \
	pdf-recursive ps-recursive uninstall-info-recursive \
	uninstall-recursive
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run aclocal-1.9
ALCC_FALSE = 
ALCC_MANPAGES = 
ALCC_TRUE = #
ALC_FALSE = 
ALC_MANPAGES = 
ALC_TRUE = #
ALLOCA = 
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run tar
AMULECMD_MANPAGES = 
AMULEWEB_DEFS = -DWITH_LIBPNG
AMULE_DAEMON_FALSE = #
AMULE_DAEMON_MANPAGES = 
AMULE_DAEMON_TRUE = 
AMULE_GUI_FALSE = 
AMULE_GUI_MANPAGES = 
AMULE_GUI_TRUE = #
AR = arm-mv5sft-linux-gnueabi-ar
AUTOCONF = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run autoconf
AUTOHEADER = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run autoheader
AUTOMAKE = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run automake-1.9
AWK = gawk
BFD_CPPFLAGS = 
BFD_LIBS = 
BUILD_CC = gcc
BUILD_CFLAGS = 
BUILD_CPPFLAGS = 
BUILD_EXEEXT = 
BUILD_INCLUDED_LIBINTL = no
BUILD_LDFLAGS = 
CAS_DEFS = 
CAS_FALSE = 
CAS_MANPAGES = 
CAS_TRUE = #
CATOBJEXT = .gmo
CC = arm-mv5sft-linux-gnueabi-gcc
CCDEPMODE = depmode=gcc3
CFLAGS = 
COMPILE_CMD_FALSE = 
COMPILE_CMD_TRUE = #
COMPILE_NLS_FALSE = 
COMPILE_NLS_TRUE = #
CPP = arm-mv5sft-linux-gnueabi-gcc -E
CPPFLAGS = -I/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../include
CRYPTOPP_CPPFLAGS =  -D__WEAK_CRYPTO__
CRYPTOPP_LDFLAGS = 
CRYPTOPP_LIBS = /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../cryptopp552/libcryptopp.a
CXX = arm-mv5sft-linux-gnueabi-g++
CXXCPP = arm-mv5sft-linux-gnueabi-g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = 
CYGPATH_W = echo
DATADIRNAME = share
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
ED2K_FALSE = #
ED2K_MANPAGES = 
ED2K_TRUE = 
EGREP = grep -E
ENABLE_IP2COUNTRY_FALSE = 
ENABLE_IP2COUNTRY_TRUE = #
ENABLE_UPNP_FALSE = 
ENABLE_UPNP_TRUE = #
EXEEXT = 
GDLIB_CFLAGS = 
GDLIB_CONFIG_PATH = 
GDLIB_LDFLAGS = 
GDLIB_LIBS = 
GENCAT = gencat
GENERATE_FLEX_HEADER_FALSE = 
GENERATE_FLEX_HEADER_TRUE = #
GEOIP_CPPFLAGS = 
GEOIP_LDFLAGS = 
GEOIP_LIBS = 
GLIBC21 = yes
GMSGFMT = :
INCINTL = 
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_SKINS_FALSE = 
INSTALL_SKINS_TRUE = #
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
INSTOBJEXT = .mo
INTLBISON = :
INTLLIBS = 
INTLOBJS = 
INTL_LIBTOOL_SUFFIX_PREFIX = 
LD = arm-mv5sft-linux-gnueabi-ld
LDFLAGS = -L/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../lib
LEX = :
LEXLIB = -lfl
LEX_OUTPUT_ROOT = 
LIBICONV = /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../lib/libiconv.so -Wl,-rpath -Wl,/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../lib
LIBINTL = 
LIBOBJS =  lstat$U.o memcmp$U.o stat$U.o strtod$U.o
LIBPNG_CFLAGS = -I/usr/local/include/libpng12
LIBPNG_CONFIG_PATH = ../libpng-1.2.39/libpng-config
LIBPNG_LDFLAGS = -L/usr/local/lib
LIBPNG_LIBS = -lpng12
LIBS = 
LIBUPNP_CFLAGS = 
LIBUPNP_CPPFLAGS = 
LIBUPNP_LDFLAGS = 
LIBUPNP_LIBS = 
LTLIBICONV = -L/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../lib -liconv -R/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/../lib
LTLIBINTL = 
LTLIBOBJS =  lstat$U.lo memcmp$U.lo stat$U.lo strtod$U.lo
MAINT = #
MAINTAINER_MODE_FALSE = 
MAINTAINER_MODE_TRUE = #
MAKEINFO = ${SHELL} /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/missing --run makeinfo
MKINSTALLDIRS = ./mkinstalldirs
MONOLITHIC_FALSE = 
MONOLITHIC_MANPAGES = 
MONOLITHIC_TRUE = #
MSGFMT = :
MSGMERGE = :
MULECFLAGS = -w  -g -ggdb -fno-inline -fmessage-length=0
MULECPPFLAGS =  -D__DEBUG__ -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -DUSE_WX_EXTENSIONS
MULECXXFLAGS = -w  -g -ggdb -fno-inline -fmessage-length=0
MULELDFLAGS =  -lpthread
MULERCFLAGS = 
NEED_CORESERVICES_FALSE = 
NEED_CORESERVICES_TRUE = #
NEED_RC_FALSE = 
NEED_RC_TRUE = #
OBJEXT = o
PACKAGE = amule
PACKAGE_BUGREPORT = admin@amule.org
PACKAGE_NAME = aMule
PACKAGE_STRING = aMule 2.2.6
PACKAGE_TARNAME = amule
PACKAGE_VERSION = 2.2.6
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
POSUB = po
POW_LIB = -lm
RANLIB = arm-mv5sft-linux-gnueabi-ranlib
RC = 
RCFLAGS = 
READLINE_LIBS = 
REGEX_LIBS = 
RESOLV_LIB = 
SET_MAKE = 
SHELL = /bin/sh
STRIP = arm-mv5sft-linux-gnueabi-strip
SVNDATE = 
SYS_WIN32_FALSE = 
SYS_WIN32_TRUE = #
USE_INCLUDED_LIBINTL = no
USE_NLS = no
VERSION = 2.2.6
WEB_FALSE = #
WEB_MANPAGES = 
WEB_TRUE = 
WXBASE_CPPFLAGS = -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib/wx/include/arm-mv5sft-linux-gnueabi-base-unicode-release-2.8 -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/include -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/contrib/include -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DwxUSE_GUI=0 -DwxUSE_GUI=0
WXBASE_LIBS = -L/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib -pthread   -Wl,-rpath,/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib -lwx_baseu_net-2.8-arm-mv5sft-linux-gnueabi -lwx_baseu-2.8-arm-mv5sft-linux-gnueabi 
WXCAS_FALSE = 
WXCAS_MANPAGES = 
WXCAS_TRUE = #
WX_CFLAGS = -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib/wx/include/arm-mv5sft-linux-gnueabi-base-unicode-release-2.8 -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/include -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/contrib/include -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DwxUSE_GUI=0 -pthread
WX_CFLAGS_ONLY = -pthread
WX_CONFIG_PATH = ../wxWidgets-2.8.9/wx-config
WX_CPPFLAGS = -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib/wx/include/arm-mv5sft-linux-gnueabi-base-unicode-release-2.8 -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/include -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/contrib/include -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DwxUSE_GUI=0
WX_CXXFLAGS = -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib/wx/include/arm-mv5sft-linux-gnueabi-base-unicode-release-2.8 -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/include -I/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/contrib/include -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DwxUSE_GUI=0 -pthread
WX_CXXFLAGS_ONLY = 
WX_DEBUG = 0
WX_LIBS = -L/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib -pthread   -Wl,-rpath,/home/patrick/nas/DNS-345_GPL/wxWidgets-2.8.9/lib -lwx_baseu_adv-2.8-arm-mv5sft-linux-gnueabi -lwx_baseu_core-2.8-arm-mv5sft-linux-gnueabi -lwx_baseu_net-2.8-arm-mv5sft-linux-gnueabi -lwx_baseu-2.8-arm-mv5sft-linux-gnueabi 
WX_LIBS_STATIC = 
WX_PORT = base
WX_RESCOMP = 
WX_SHARED = 1
WX_UNICODE = 
WX_VERSION_FULL = 2.8.9
WX_VERSION_MAJOR = 2
WX_VERSION_MINOR = 8
X11LIBS = 
XGETTEXT = :
YACC = yacc
ZLIB_CPPFLAGS = -I/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/..//include
ZLIB_LDFLAGS = -L/home/patrick/nas/DNS-345_GPL/aMule-2.2.6/..//lib
ZLIB_LIBS = -lz
ac_ct_AR = 
ac_ct_BUILD_CC = gcc
ac_ct_CC = 
ac_ct_CXX = 
ac_ct_LD = 
ac_ct_RANLIB = 
ac_ct_RC = 
ac_ct_STRIP = 
ac_pt_PKG_CONFIG = /usr/bin/pkg-config
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__fastdepCXX_FALSE = #
am__fastdepCXX_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
datadir = ${prefix}/share
docdir = ${prefix}/share/doc/aMule-2.2.6
exec_prefix = ${prefix}
host = arm-mv5sft-linux-gnueabi
host_alias = arm-mv5sft-linux-gnueabi
host_cpu = arm
host_os = linux-gnueabi
host_vendor = mv5sft
includedir = ${prefix}/include
infodir = ${prefix}/info
install_sh = /home/patrick/nas/DNS-345_GPL/aMule-2.2.6/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
mkdir_p = mkdir -p --
oldincludedir = /usr/include
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 
SUBDIRS = cpp
MAINTAINERCLEANFILES = Makefile.in
BUILT_SOURCES = ECGeneratedFiles
ECGeneratedFilesSources = \
	abstracts/ECTagTypes.abstract \
	abstracts/ECCodes.abstract
EXTRA_DIST = file_generator.pl
EXTRA__DIST__SUBDIRS = abstracts java		# c# cannot be included because of the # in the name
DISTCLEANFILES = $(BUILT_SOURCES)
all: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) all-recursive
.SUFFIXES:
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am $(top_srcdir)/automake/dist-hook.am $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  src/libs/ec/Makefile'>/dev/null; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  src/libs/ec/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'>/dev/null; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe) denoiser;; \
	esac;
$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(top_srcdir)/configure: # $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
uninstall-info-am:
$(RECURSIVE_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir">/dev/null; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"
mostlyclean-recursive clean-recursive distclean-recursive \
maintainer-clean-recursive:
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir">/dev/null; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done
ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS
TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique
GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here
distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
distdir: $(DISTFILES)
	$(mkdir_p) $(distdir)/../../../automake
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(mkdir_p) "$(distdir)/$$subdir" \
	    || exit 1; \
	    distdir=`$(am__cd) $(distdir) && pwd`; \
	    top_distdir=`$(am__cd) $(top_distdir) && pwd`; \
	    (cd $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$top_distdir" \
	        distdir="$$distdir/$$subdir" \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-recursive
all-am: Makefile
installdirs: installdirs-recursive
installdirs-am:
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive
install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:
clean-generic:
distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)
maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-recursive
clean-am: clean-generic mostlyclean-am
distclean: distclean-recursive
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-tags
dvi: dvi-recursive
dvi-am:
html: html-recursive
info: info-recursive
info-am:
install-data-am:
install-exec-am:
install-info: install-info-recursive
install-man:
installcheck-am:
maintainer-clean: maintainer-clean-recursive
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic
mostlyclean: mostlyclean-recursive
mostlyclean-am: mostlyclean-generic
pdf: pdf-recursive
pdf-am:
ps: ps-recursive
ps-am:
uninstall-am: uninstall-info-am
uninstall-info: uninstall-info-recursive
.PHONY: $(RECURSIVE_TARGETS) CTAGS GTAGS all all-am check check-am \
	clean clean-generic clean-recursive ctags ctags-recursive \
	dist-hook distclean distclean-generic distclean-recursive \
	distclean-tags distdir dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	maintainer-clean-recursive mostlyclean mostlyclean-generic \
	mostlyclean-recursive pdf pdf-am ps ps-am tags tags-recursive \
	uninstall uninstall-am uninstall-info-am
ECGeneratedFiles: $(ECGeneratedFilesSources)
	$(srcdir)/file_generator.pl $(srcdir) $(ECGeneratedFilesSources);
	echo $(ECGeneratedFilesSources) > ECGeneratedFiles
dist-hook:
	test -z "$(EXTRA__DIST__SUBDIRS)" || \
	for d in $(EXTRA__DIST__SUBDIRS) ; do \
		mkdir $(distdir)/$$d ; \
		for f in `find $(srcdir)/$$d -name '.svn' -prune -o -printf "%P\n"` ; do \
			if test -d $(srcdir)/$$d/$$f ; then \
				mkdir $(distdir)/$$d/$$f ; \
			else \
				cp -p $(srcdir)/$$d/$$f $(distdir)/$$d/$$f ; \
			fi ; \
		done ; \
	done
.NOEXPORT:
