# $Id: Makefile,v 1.1.1.1 2009/10/09 03:04:07 jack Exp $

COPY=	transapp.cs writetest.cs
BUILD=	admin.html \
	app.html \
	archival.html \
	atomicity.html \
	checkpoint.html \
	cursor.html \
	data_open.html \
	deadlock.html \
	env_open.html \
	fail.html \
	faq.html \
	filesys.html \
	hotfail.html \
	inc.html \
	intro.html \
	logfile.html \
	nested.html \
	put.html \
	read.html \
	reclimit.html \
	recovery.html \
	term.html \
	throughput.html \
	tune.html \
	why.html

all: ${BUILD}
