# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:23 jack Exp $

BUILD=  callback.html db_dump.html disk.html handle.html incomplete.html \
	intro.html mutexlock.html notfound.html renumber.html \
	set_flags.html toc.html tx_recover.html

all: ${BUILD}
