# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:24 jack Exp $

BUILD=	cursor.html \
	disk.html \
	event.html \
	full_election.html \
	intro.html \
	memp_fput.html \
	memp_fset.html \
	toc.html \
	verb.html \
	verbose.html \
	win.html

all: ${BUILD}
