# $Id: Makefile,v 1.1.1.1 2009/04/20 07:15:22 jack Exp $

BUILD=  am_conv.html cam_conv.html config.html dead.html deaddbg.html \
	intro.html max.html nondb.html notxn.html page.html stdmode.html \
	timeout.html twopl.html

all: ${BUILD}
