# $Id: Makefile,v 1.1.1.1 2009/10/09 03:04:22 jack Exp $

BUILD=  berkeley_db_svc.html db_archive.html db_checkpoint.html \
	db_codegen.html db_deadlock.html db_dump.html db_hotbackup.html \
	db_load.html db_printlog.html db_recover.html db_stat.html \
	db_upgrade.html db_verify.html index.html

XML=	index.html dbxml_dump.html dbxml_load.html dbxmlsh.html \
	load_container.html
