# $Id: Makefile,v 1.1.1.1 2009/10/09 03:03:56 jack Exp $

COMMON=	env_cdsgroup_begin.html \
	env_set_lk_conflicts.html \
	env_set_lk_detect.html \
	env_set_lk_max_lockers.html \
	env_set_lk_max_locks.html \
	env_set_lk_max_objects.html \
	env_set_lk_partitions.html \
	lock_class.html \
	lock_detect.html \
	lock_get.html \
	lock_id.html \
	lock_id_free.html \
	lock_list.html \
	lock_put.html \
	lock_stat.html \
	lock_vec.html

CXX=	deadlock_class.html \
	lockng_class.html
