# $Id: Makefile,v 1.1.1.1 2009/10/09 03:04:16 jack Exp $

BUILD=  cksum.html client.html del.html disk.html intro.html java.html \
	lockng.html nosync.html priority.html queue.html repinit.html \
	tcl.html toc.html verify.html

all: ${BUILD}
