# $Id: Makefile,v 1.1.1.1 2009/10/09 03:03:58 jack Exp $

BUILD=  close.html count.html curclose.html curdel.html curdup.html \
	curget.html curput.html cursor.html delete.html get.html \
	join.html open.html opensub.html ops.html put.html second.html \
	stat.html sync.html truncate.html upgrade.html verify.html
COPY=	second.javas

all: ${BUILD}
