# $Id: Makefile,v 1.1.1.1 2009/10/09 03:04:00 jack Exp $

BUILD=	align.html dbsizes.html diskspace.html error.html faq.html \
	get_bulk.html partial.html perm.html stability.html struct.html \
	tune.html

all: ${BUILD}
