# $Id: Makefile,v 1.1.1.1 2009/10/09 03:04:22 jack Exp $

COMMON=	env_set_tx_max.html \
	env_set_tx_timestamp.html \
	txn_abort.html \
	txn_begin.html \
	txn_checkpoint.html \
	txn_class.html \
	txn_commit.html \
	txn_discard.html \
	txn_id.html \
	txn_list.html \
	txn_prepare.html \
	txn_recover.html \
	txn_set_name.html \
	txn_set_timeout.html \
	txn_stat.html
